# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Feature Requests Board
    url: https://github.com/Finsys/dockhand/discussions/categories/ideas
    about: Share ideas with other users
